services:
  - type: web
    name: food-scanner-api
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: food_scanner
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --app-dir src --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
